# Generated by Django 5.2.16 on 2026-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_location_and_demo_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CRE', 'CRE'), ('SO', 'PS/SO'), ('RECEPTIONIST', 'Receptionist')], default='CRE', max_length=20),
        ),
    ]
