# Generated by Django 5.2.16 on 2026-09-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CRE', 'CE'), ('SO', 'PS/SO'), ('SALES_MANAGER', 'Sales Manager'), ('RECEPTIONIST', 'Receptionist'), ('COMPLAINTS', 'Complaints department')], default='CRE', max_length=20),
        ),
    ]
