# Generated by Django 5.2.16 on 2026-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CEO', 'CEO'), ('CRE', 'CE'), ('SO', 'PS/SO'), ('SALES_MANAGER', 'Sales Manager'), ('RECEPTIONIST', 'Receptionist'), ('COMPLAINTS', 'Complaints department'), ('FEEDBACK', 'Feedback Caller')], default='CRE', max_length=20),
        ),
    ]
