# Generated by Django 5.2.16 on 2026-09-12 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0004_complaint_subtype'),
        ('leads', '0018_seed_river_indie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('retail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_account', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('REVERSAL', 'Reversal'), ('VALUATION', 'Sale value revision')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('occurred_on', models.DateField(db_index=True)),
                ('method', models.CharField(blank=True, choices=[('', 'Not applicable'), ('CASH', 'Cash'), ('BANK', 'Bank transfer'), ('UPI', 'UPI'), ('CARD', 'Card'), ('FINANCE', 'Finance disbursement'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(max_length=500)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='ceo.financialentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ceo.saleaccount')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('branch', models.CharField(max_length=120)),
                ('enquiries', models.PositiveIntegerField(default=0)),
                ('test_drives', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('retails', models.PositiveIntegerField(default=0)),
                ('retail_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='ceo.salestarget')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('E', 'Enquiry'), ('T', 'Test drive'), ('B', 'Booking'), ('R', 'Retail')], max_length=1)),
                ('occurred_on', models.DateField(db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(null=True)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=120)),
                ('rto', models.CharField(blank=True, max_length=5)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=160)),
                ('activity', models.CharField(blank=True, max_length=160)),
                ('sub_activity', models.CharField(blank=True, max_length=160)),
                ('model_interest', models.CharField(blank=True, max_length=100)),
                ('provenance', models.CharField(default='recorded', max_length=20)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceo_milestones', to=settings.AUTH_USER_MODEL)),
                ('cre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceo_cre_milestones', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='leads.lead')),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceo_so_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'occurred_on', 'branch'], name='ceo_milesto_kind_76c223_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'kind'), name='ceo_first_lead_milestone')],
            },
        ),
        migrations.CreateModel(
            name='OperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=60)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source_key', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=120)),
                ('snapshot', models.JSONField(default=dict)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='recorded', max_length=20)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_events', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_events', to='complaints.complaint')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['lead', 'occurred_at'], name='ceo_operati_lead_id_cb6966_idx'), models.Index(fields=['actor', 'occurred_at'], name='ceo_operati_actor_i_6fab91_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='saleaccount',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_amount__gte', 0), ('agreed_amount__isnull', True), _connector='OR'), name='ceo_positive_agreed'),
        ),
        migrations.AddConstraint(
            model_name='saleaccount',
            constraint=models.CheckConstraint(condition=models.Q(('retail_amount__gte', 0), ('retail_amount__isnull', True), _connector='OR'), name='ceo_positive_retail'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(condition=models.Q(('so__isnull', False)), fields=('month', 'branch', 'so'), name='ceo_so_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(condition=models.Q(('so__isnull', True)), fields=('month', 'branch'), name='ceo_branch_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.CheckConstraint(condition=models.Q(('retail_value__gte', 0)), name='ceo_positive_target_value'),
        ),
    ]
