# Generated by Django 5.2.16 on 2026-09-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_seed_river_indie'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('enrolled_at', models.DateTimeField(null=True)),
                ('last_so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contact', to='leads.lead')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INTRODUCTION', 'SO introduction'), ('REASSIGNMENT', 'SO changed')], max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=20)),
                ('template', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('variables', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview only — not sent'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled — not sent')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='leads.lead')),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('source_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_message', to='leads.leadaudit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
