# Generated by Django 5.2.16 on 2026-09-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('notifications', '0002_whatsappcontact_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='feedback_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktask'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('FOLLOW_UP', 'Follow-up'), ('OVERDUE', 'Overdue'), ('FEEDBACK_ASSIGNED', 'Feedback assigned'), ('FEEDBACK_DUE', 'Feedback due'), ('FEEDBACK_OVERDUE', 'Feedback overdue')], max_length=20),
        ),
    ]
