# Generated by Django 5.2.16 on 2026-09-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_dedupe_key_notification_feedback_task_and_more'),
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicing.servicerequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SERVICE_UPDATE', 'Service update'), ('ASSIGNMENT', 'Assignment'), ('FOLLOW_UP', 'Follow-up'), ('OVERDUE', 'Overdue'), ('FEEDBACK_ASSIGNED', 'Feedback assigned'), ('FEEDBACK_DUE', 'Feedback due'), ('FEEDBACK_OVERDUE', 'Feedback overdue')], max_length=20),
        ),
    ]
