# Generated by Django 5.2.16 on 2026-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_service_request_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SERVICE_UPDATE', 'Service update'), ('ASSIGNMENT', 'Assignment'), ('FOLLOW_UP', 'Follow-up'), ('OVERDUE', 'Overdue'), ('FEEDBACK_ASSIGNED', 'Feedback assigned'), ('FEEDBACK_DUE', 'Feedback due'), ('FEEDBACK_ISSUE', 'Feedback needs attention'), ('FEEDBACK_OVERDUE', 'Feedback overdue')], max_length=20),
        ),
    ]
