# Generated by Django 5.2.16 on 2026-09-12 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0018_seed_river_indie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('origin', models.CharField(choices=[('WEBSITE', 'Website'), ('META', 'Meta')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('secret_ref', models.SlugField(max_length=100)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=False)),
                ('paused_reason', models.CharField(blank=True, max_length=80)),
                ('last_receipt_at', models.DateTimeField(blank=True, null=True)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate_window', models.DateTimeField(blank=True, null=True)),
                ('rate_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('external_id', models.CharField(max_length=160)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkpoint', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconcile_lease_until', models.DateTimeField(blank=True, null=True)),
                ('reconcile_error', models.CharField(blank=True, max_length=80)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='intake.connection')),
            ],
        ),
        migrations.CreateModel(
            name='MappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField()),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='intake.intakeform')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160)),
                ('identity', models.CharField(max_length=330)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=list)),
                ('ignored_labels', models.JSONField(default=list)),
                ('answers_expired', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('mapped_values', models.JSONField(default=dict)),
                ('corrections', models.JSONField(default=dict)),
                ('campaign_name', models.CharField(blank=True, max_length=160)),
                ('attribution', models.JSONField(default=dict)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=10)),
                ('state', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('IMPORTED', 'Imported'), ('LINKED', 'Linked'), ('FAILED', 'Failed'), ('DISMISSED', 'Dismissed')], db_index=True, default='RECEIVED', max_length=20)),
                ('errors', models.JSONField(default=dict)),
                ('review_reason', models.CharField(blank=True, db_index=True, max_length=40)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.submission')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='intake.connection')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='intake.intakeform')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_submissions', to='leads.lead')),
                ('mapping_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intake.mappingversion')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intake.connection')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.lead')),
                ('mapping_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intake.mappingversion')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='intake.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='intakeform',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='intake_connection_form_unique'),
        ),
        migrations.AddConstraint(
            model_name='intakeform',
            constraint=models.UniqueConstraint(condition=models.Q(('page_id', ''), _negated=True), fields=('page_id', 'external_id'), name='intake_meta_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='mappingversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('form__isnull', False), ('template_name', '')), models.Q(('form__isnull', True), models.Q(('template_name', ''), _negated=True)), _connector='OR'), name='intake_mapping_scope'),
        ),
        migrations.AddConstraint(
            model_name='mappingversion',
            constraint=models.UniqueConstraint(condition=models.Q(('form__isnull', False)), fields=('form', 'version'), name='intake_form_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='mappingversion',
            constraint=models.UniqueConstraint(condition=models.Q(('form__isnull', True)), fields=('template_name', 'version'), name='intake_template_version_unique'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['state', 'next_attempt_at'], name='intake_subm_state_8954c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('connection', 'identity'), name='intake_external_identity_unique'),
        ),
    ]
