# Generated by Django 5.2.16 on 2026-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='fetch_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='reconcile_cursor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='reconcile_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='reconcile_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
