# Generated by Django 5.2.16 on 2026-08-24 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0010_remove_calllog_other_so_called'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_phone', models.CharField(db_index=True, max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('SERVICE_DELAY', 'Service Delay'), ('PRODUCT_DEFECT', 'Product Defect'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('BILLING_FINANCE', 'Billing / Finance'), ('AFTER_SALES', 'After-Sales'), ('STAFF_BEHAVIOUR', 'Staff Behaviour'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model_interest', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WALKIN', 'Walk-in'), ('SOCIAL_MEDIA', 'Social Media'), ('OTHER', 'Other')], default='PHONE', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_complaints', to=settings.AUTH_USER_MODEL)),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_notes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['logged_by', 'status'], name='complaints__logged__b78531_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category', 'created_at'], name='complaints__categor_37b8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority', 'status'], name='complaints__priorit_9b6e83_idx'),
        ),
    ]
