# Generated by Django 5.2.16 on 2026-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_queue_inactive_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subtype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
