# Generated by Django 5.2.16 on 2026-07-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PARSING', 'Parsing'), ('READY', 'Ready for review'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PARSING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_ok', models.PositiveIntegerField(default=0)),
                ('duplicates_found', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('normalized_phone', models.CharField(blank=True, max_length=10)),
                ('validation_error', models.CharField(blank=True, max_length=255)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending'), ('SKIP', 'Skip'), ('OVERWRITE', 'Overwrite'), ('IMPORT', 'Import as new')], default='IMPORT', max_length=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='uploads.uploadbatch')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
            ],
        ),
    ]
