# Generated by Django 5.2.16 on 2026-09-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='mapping_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intake.mappingversion'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='original_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadrow',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='uploadrow',
            name='answers_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadrow',
            name='ignored_labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='uploadrow',
            name='resolution_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadrow',
            name='validation_errors',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uploadrow',
            name='validation_error',
            field=models.TextField(blank=True),
        ),
    ]
