# Generated by Django 5.2.16 on 2026-07-24 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('META', 'Meta Ads'), ('WEBSITE', 'Website'), ('CARWALE', 'CarWale'), ('WALKIN', 'Walk-in'), ('CAMPAIGN', 'Campaign'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('source_label', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=160)),
                ('model_interest', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('RNR', 'RNR'), ('CALLBACK', 'Callback Scheduled'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('WALKIN', 'Walk-in Booked'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='FRESH', max_length=20)),
                ('duplicate_flag', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('RNR', 'RNR'), ('CALLBACK', 'Callback Scheduled'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('WALKIN', 'Walk-in Booked'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='leads.lead')),
            ],
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_so', 'status'], name='leads_lead_assigne_6b38ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='leads_lead_source_ebb051_idx'),
        ),
    ]
