# Generated by Django 5.2.16 on 2026-07-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('buying_timeline', models.CharField(blank=True, max_length=80)),
                ('finance_type', models.CharField(blank=True, max_length=80)),
                ('trade_in', models.BooleanField(blank=True, null=True)),
                ('test_drive', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='calllog',
            name='outcome',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], db_index=True, default='WARM', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='sales_outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('RETAILED', 'Retailed'), ('LOST', 'Lost')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_so', 'category'], name='leads_lead_assigne_24c82b_idx'),
        ),
        migrations.AddField(
            model_name='leadqualification',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadqualification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_qualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
