# Generated by Django 5.2.16 on 2026-08-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_assigned_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='flagged_to_manager',
            field=models.BooleanField(default=False),
        ),
    ]
