# Generated by Django 5.2.16 on 2026-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_calllog_call_status_lead_flagged_to_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
