# Generated by Django 5.2.16 on 2026-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='other_so_called',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
