# Generated by Django 5.2.16 on 2026-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_calllog_other_so_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
