# Generated by Django 5.2.16 on 2026-09-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='activity',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_activity',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
