# Generated by Django 5.2.16 on 2026-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='test_drive_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
