# Generated by Django 5.2.16 on 2026-09-17 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_seed_river_indie'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a six-digit pincode starting with 1–9.', regex='\\A[1-9][0-9]{5}\\Z')]),
        ),
    ]
