# Generated by Django 5.2.16 on 2026-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rto',
            field=models.CharField(blank=True, choices=[('KL-01', 'Thiruvananthapuram'), ('KL-02', 'Kollam'), ('KL-03', 'Pathanamthitta'), ('KL-04', 'Alappuzha'), ('KL-05', 'Kottayam'), ('KL-06', 'Idukki'), ('KL-07', 'Ernakulam'), ('KL-08', 'Thrissur'), ('KL-09', 'Palakkad'), ('KL-10', 'Malappuram'), ('KL-11', 'Kozhikode'), ('KL-12', 'Wayanad'), ('KL-13', 'Kannur'), ('KL-14', 'Kasargod'), ('KL-15', 'KSRTC'), ('KL-16', 'Attingal'), ('KL-17', 'Muvattupuzha'), ('KL-18', 'Vadakara'), ('KL-19', 'Parassala'), ('KL-20', 'Neyyattinkara'), ('KL-21', 'Nedumangad'), ('KL-22', 'Kazhakoottam'), ('KL-23', 'Karunagappalli'), ('KL-24', 'Kottarakkara'), ('KL-25', 'Punalur'), ('KL-26', 'Adoor'), ('KL-27', 'Thiruvalla'), ('KL-28', 'Mallappally'), ('KL-29', 'Kayamkulam'), ('KL-30', 'Chengannur'), ('KL-31', 'Mavelikkara'), ('KL-32', 'Cherthala'), ('KL-33', 'Changanassery'), ('KL-34', 'Kanjirappally'), ('KL-35', 'Pala'), ('KL-36', 'Vaikom'), ('KL-37', 'Vandiperiyar'), ('KL-38', 'Thodupuzha'), ('KL-39', 'Thripunithura'), ('KL-40', 'Perumbavoor'), ('KL-41', 'Aluva'), ('KL-42', 'North Paravur'), ('KL-43', 'Mattancherry'), ('KL-44', 'Kothamangalam'), ('KL-45', 'Irinjalakuda'), ('KL-46', 'Guruvayur'), ('KL-47', 'Kodungalloor'), ('KL-48', 'Wadakkanchery'), ('KL-49', 'Alathur'), ('KL-50', 'Mannarkkad'), ('KL-51', 'Ottappalam'), ('KL-52', 'Pattambi'), ('KL-53', 'Perinthalmanna'), ('KL-54', 'Ponnani'), ('KL-55', 'Tirur'), ('KL-56', 'Koyilandy'), ('KL-57', 'Koduvally'), ('KL-58', 'Thalassery'), ('KL-59', 'Taliparamba'), ('KL-60', 'Kanhangad'), ('KL-61', 'Kunnathur'), ('KL-62', 'Ranni'), ('KL-63', 'Angamaly'), ('KL-64', 'Chalakkudy'), ('KL-65', 'Tirurangadi'), ('KL-66', 'Kuttanad'), ('KL-67', 'Uzhavoor'), ('KL-68', 'Devikulam'), ('KL-69', 'Udumbanchola'), ('KL-70', 'Chittur'), ('KL-71', 'Nilambur'), ('KL-72', 'Mananthavady'), ('KL-73', 'Sulthan Bathery'), ('KL-74', 'Kattakkada'), ('KL-75', 'Thriprayar'), ('KL-76', 'Nanmanda'), ('KL-77', 'Perambra'), ('KL-78', 'Iritty'), ('KL-79', 'Vellarikundu'), ('KL-80', 'Pathanapuram'), ('KL-81', 'Varkala'), ('KL-82', 'Chadayamangalam'), ('KL-83', 'Konni'), ('KL-84', 'Kondotty'), ('KL-85', 'Ramanattukara'), ('KL-86', 'Payyannur')], db_index=True, max_length=5),
        ),
    ]
