# Generated by Django 5.2.16 on 2026-09-23 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_subtype'),
        ('leads', '0020_update_rto_names'),
        ('servicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='origin',
            field=models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], db_index=True, default='OUTBOUND', max_length=8),
        ),
        migrations.CreateModel(
            name='InboundInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=24)),
                ('caller_name', models.CharField(blank=True, max_length=160)),
                ('caller_phone', models.CharField(blank=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField()),
                ('state', models.CharField(choices=[('RECORDED', 'Recorded'), ('UNMATCHED', 'Unmatched customer'), ('AWAITING_ROUTING', 'Awaiting routing'), ('RESOLVED', 'Reviewed')], db_index=True, default='RECORDED', max_length=20)),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('owner_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.complaint')),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_interactions', to='leads.followup')),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_interactions', to='leads.lead')),
                ('review_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='leads.inboundinteraction')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicing.servicerequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
