# Generated by Django 5.2.16 on 2026-09-12 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0018_seed_river_indie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TDF', 'Test drive feedback'), ('PBF', 'Post booking feedback'), ('PSF', 'Post sales feedback')], max_length=3)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('UNREACHABLE', 'Unreachable'), ('DECLINED', 'Declined'), ('INVALID_NUMBER', 'Invalid number')], db_index=True, default='OPEN', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('original_due_at', models.DateTimeField(db_index=True)),
                ('next_call_at', models.DateTimeField(db_index=True)),
                ('unsuccessful_attempts', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('on_time', models.BooleanField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tasks', to='leads.lead')),
                ('source_audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.leadaudit')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('outcome', models.CharField(choices=[('COLLECTED', 'Feedback collected'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched off'), ('CALLBACK', 'Customer requested callback'), ('DECLINED', 'Declined'), ('INVALID_NUMBER', 'Invalid number')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField()),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='feedback.feedbacktask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_branch', models.CharField(blank=True, max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_assignments', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_feedback_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='feedback.feedbacktask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbacktask',
            index=models.Index(fields=['assigned_to', 'status', 'next_call_at'], name='feedback_fe_assigne_af0f80_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktask',
            constraint=models.UniqueConstraint(fields=('lead', 'kind'), name='feedback_once_per_lead_kind'),
        ),
    ]
