# Generated by Django 5.2.16 on 2026-09-21 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_subtype'),
        ('feedback', '0002_activate_feedback'),
        ('leads', '0020_update_rto_names'),
        ('servicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=12)),
                ('reason', models.TextField()),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackIssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], max_length=12)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('preferred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='feedbacktask',
            name='feedback_once_per_lead_kind',
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='further_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='help_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='origin',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Requested feedback'), ('HISTORICAL', 'Historical catch-up')], default='AUTOMATIC', max_length=12),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='service_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_task', to='servicing.serviceevent'),
        ),
        migrations.AlterField(
            model_name='feedbacktask',
            name='kind',
            field=models.CharField(choices=[('TDF', 'Test drive feedback'), ('PBF', 'Post booking feedback'), ('PSF', 'Post sales feedback'), ('SVC', 'Service feedback'), ('GEN', 'Requested feedback')], max_length=3),
        ),
        migrations.AlterField(
            model_name='feedbacktask',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tasks', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='feedbacktask',
            name='source_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.leadaudit'),
        ),
        migrations.AlterField(
            model_name='feedbacktask',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('UNREACHABLE', 'Unreachable'), ('DECLINED', 'Declined'), ('INVALID_NUMBER', 'Invalid number'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackissue',
            name='acknowledged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_feedback_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackissue',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_issue', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='feedbackissue',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_feedback_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackissue',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issue', to='feedback.feedbacktask'),
        ),
        migrations.AddField(
            model_name='feedbackissueevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackissueevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='feedback.feedbackissue'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_requests', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_feedback_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='manual_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='feedback.feedbackrequest'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktask',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['TDF', 'PBF', 'PSF'])), fields=('lead', 'kind'), name='feedback_once_per_sales_kind'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktask',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'GEN'), ('status', 'OPEN')), fields=('lead',), name='feedback_one_open_request'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktask',
            constraint=models.CheckConstraint(condition=models.Q(('satisfaction__isnull', True), ('satisfaction__range', (1, 5)), _connector='OR'), name='feedback_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['TDF', 'PBF', 'PSF']), ('lead__isnull', False), ('manual_request__isnull', True), ('service_event__isnull', True), ('source_audit__isnull', False)), models.Q(('kind', 'SVC'), ('lead__isnull', True), ('manual_request__isnull', True), ('service_event__isnull', False), ('source_audit__isnull', True)), models.Q(('kind', 'GEN'), ('lead__isnull', False), ('manual_request__isnull', False), ('service_event__isnull', True), ('source_audit__isnull', True)), _connector='OR'), name='feedback_valid_source'),
        ),
        migrations.AddConstraint(
            model_name='feedbackrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('lead',), name='feedback_one_pending_request'),
        ),
    ]
